### ISSUE TITLE
MNTP: Database hits

### ISSUE THREAD

**Issue by tomfulton** [Jeavon/Umbraco-Core-Property-Value-Converters#5]
In doing some profiling of our APIs, I've noticed the MNTP converter causes database calls to occur for each selected node, when it uses the [EntityService to determine the node type](https://github.com/Jeavon/Umbraco-Core-Property-Value-Converters/blob/v2/Our.Umbraco.PropertyConverters/MultiNodeTreePickerPropertyConverter.cs#L123).

Not really a bug, but I would imagine it's ideal to not have any database hits for front-end queries.  Any ideas for how we can remove these?  Some thoughts for a starting point:
- Maintain a cache of Node ID to Node Object Types as we retrieve them.  We probably wouldn't have to worry about invalidating it since I don't think you can change the underlying type of an existing node.
- Instead of using EntityService to determine the desired type, can we use the value of the "Node Object Type" dropdown in the prevalues?  Though this may require a DB hit to look up as well, but it'd be only one per property rather than one per selected node.
- Use some other, front-end friendly way of retrieving the node's object type from the ID.  Not sure this exists at the moment...

**Comment by Jeavon** [comment]
Ha, well before your issue #1 I used to check only the first node type and assume the rest were the same (a safe assumption to make). As I hopefully fixed the underlying PetoPoco bug in Umbraco v7.2 I will be reverting to that in the next release (but it will of course up the Umbraco dependancy to v7.2).

One of my todo's on this project was to implement a cache of the conversions so that only the first conversion made the DB hits. Weighing that up against the fact that many people who are really optimising are implementing output caching it seemed it might be wasted effort.  Also as my converter implementation is complete, it is ready for the Umbraco v8 object cache where the values will be cached automatically....

**Comment by Jeavon** [comment]
I have sort of reverted to how it was before with a new dependency on Umbraco v7.2.1 which will certainly reduce the DB hits. Would love it if you could try it out? We have a MyGet feed for builds now at https://www.myget.org/gallery/umbraco-core-property-value-converters

**Comment by Jeavon** [comment]
v2.1.5 doesn't make any DB for the MNTP converter thanks to #8
